== CUIE Assignment 1 - interaktives Custom Control

=== Bearbeitet von

* Hanna Lisa Franz

Am BärnHäckt-Hackathon haben wir dieses Jahr ein Konzept für eine App erstellt, die Filme anhand des Gemütszustandes des Benutzers vorschlägt. Das UI-Konzept enthält viele Custom UI Elemente: (https://www.figma.com/file/oLb9oKxtfx9XehHnwopQT8/bernhackt_fr%C3%BCndinne_2019?node-id=0%3A1)[Figma Link]).

Eines davon ist ein Slider, mit dem der User angeben soll, wie glücklich er ist.
Dieses Custom Control Element habe ich hier umgesetzt.


=== Abgabe

* Dienstag, 15.10.2019, 12:00 Uhr
* Die Abgabe erfolgt durch ein "Push" auf den Master-Branch Ihres GitHub-Repositories.

=== Initiale Schritte

* Tragen Sie ihren Namen unter "Bearbeitet von" ein. Manche GitHub-Account-Namen können nicht
 eindeutig einer Person zugeordnet werden.

* Benennen Sie das Package "assignment_1" um. Verwenden Sie Ihren GitHub-Account-Namen. (Via "Refactor -&gt; Rename…")

* Pushen Sie diese Änderungen sofort ins Git-Repository (z.B. via "VCS -&gt; Commit… -&gt; Commit&amp;Push")

=== Bitte beachten Sie

* Es wird empfohlen die Assignment-Aufgaben, genau wie das Programmierprojekt, in einem 2er-Team zu bearbeiten.

* Falls Sie das Assignment zu zweit bearbeiten:
** tragen Sie beide Namen unter "Bearbeitet von" ein
** arbeiten Sie ausschliesslich in einem Repository
** falls sie beide Zugang zu diesem Repository wollen: tragen Sie die zweite Person als "Collaborator" ein (auf GitHub unter "Settings - &gt; Collaborators &amp; teams")
** löschen Sie das nicht benötigte Repository (auf GitHub unter "Settings")
** arbeiten Sie gemeinsam und gleichzeitig an den Aufgaben (Stichwort: Pair-Programming)
** https://www.it-agile.de/wissen/agiles-engineering/pair-programming/[Pair-Programming] heisst insbesondere, dass beide Teammitglieder zu gleichen Teilen aktiv in der Entwickler-Rolle sind. Einem Entwickler lediglich bei seiner Arbeit zuzuschauen ist kein Pair-Programming.
** das Aufteilen und separate Bearbeiten von Teil-Aufgaben ist nicht erwünscht
* Ausdrücklich erlaubt und erwünscht ist, dass Sie sich gegebenenfalls Hilfe holen.
Das Programmierzentrum ist geöffnet und Nachfragen werden zum Beispiel über den im Repository integrierten
Issue Tracker oder per Mail gerne beantwortet.

=== Die Aufgabe: Einfaches, interaktives Custom Control

Entwerfen und implementieren Sie ein einfaches, _interaktives_ Custom Control.
 - Entwerfen Sie ein interaktives Custom Control mit Hilfe eines Grafik-Programms.
 - Übertragen Sie den Entwurf in ein Java-Programm und implementieren Sie dieses Custom Control auf Basis JavaFX.
 - Verwenden Sie die im Unterricht besprochene und als Template in diesem Repository mitgelieferte Grundstruktur (das "Template").
 - Grafisch sehr einfache Custom Controls reichen für dieses Assignment vollkommen aus. Im Mittelpunkt steht die Anwendung
 der im Unterricht vorgestellten Vorgehensweise und der erarbeiteten Grundstruktur.

Der Entwurf des Custom Controls im Grafik-Programm ist Bestandteil der Aufgabe. Der entsprechende File muss mit abgegeben werden.

Welches Custom Control Sie implementieren ist Ihnen freigestellt. Einzige Einschränkung: Custom Controls, die bereits
im Unterricht detailliert besprochen wurden (LED, NumberRange, etc.) sind ausgeschlossen. Dagegen können Sie gerne
ein Control umsetzen, das bereits als Screendump oder als Demo gezeigt wurde.

=== Bewertung

* Es können in diesem Assignment maximal 2 Punkte erreicht werden.

* Einen Punkt gibt es bereits sobald der ernsthafte Wille ein Custom Control auf Basis des Templates zu implementieren erkennbar ist.

* Für zwei Punkte muss das Custom Control tatsächlich interaktiv sein und das Template sinnvoll angewendet werden.
 Mit einem reinen Anzeigeelement (keine Wertänderung via Custom Control durch den Benutzer) kann maximal 1 Punkt erreicht werden.

* 0 Punkte gibt es
** der Java-Code nicht komplierfähig ist
** das im Template enthaltene "Custom Control" nicht deutlich erkennbar verändert wurde
** für Plagiate
** falls kein aktiver Beitrag eines der beiden Teammitglieder an der Lösung erkennbar ist
** im Zweifelsfall wird ein Code-Walkthrough durchgeführt

* In Ausnahmefällen kann es dazu kommen, dass Teammitglieder unterschiedliche Punkte erhalten.


=== Bei Problemen mit dem IntelliJ-Setup
Es kommt immer wieder mal vor, dass der Setup des IntelliJ-Projekts nicht auf Anhieb funktioniert oder "plötzlich"
nicht mehr funktioniert.

Sie brauchen in so einem Fall NICHT nochmal den Invitation-Link annehmen oder das Projekt via “Check out from Version Control” oder "git clone …" nochmal anlegen.

Statt dessen den IntelliJ-Setup neu generieren lassen. Dazu verwendet man den File "build.gradle", der eine
komplette und IDE-unabhängige Projektbeschreibung enthält.

Die einzelnen Schritte:

* Schliessen Sie alle geöffneten Projekte (File -&gt; Close Project)

* Wählen Sie “OPEN”

* Es erscheint ein Finder-Fenster mit dem Sie zu ihrem Projekt navigieren.

* Dort wählen Sie den File “build.gradle” aus.

* Beim nächsten Dialog “Open as Project” wählen. Wenn alles gut gegangen ist sollte im Project-View der Java-Ordner unter src/main blau sein und der Java-Ordner unter src/test grün.
